"use strict";
let car = "subaru";
console.log("Is car == 'subaru'? I predict True.");
console.log(car === 'subaru');
console.log("Is car ! == 'honda city'?  predict true.");
console.log(car == 'honda city');
console.log("Is car === 'Subaru'? I predict False.");
console.log(car === 'Subaru');
console.log("Is car === 'SABARU'? I predict False.");
console.log(car === 'SABARU');
console.log("Is car.length > 6?  predict true.");
console.log(car.length > 6);
console.log("Is car.length > !=10?  predict true.");
console.log(car.length > 10);
console.log("is 10 > 45 ? predict false");
console.log(10 > 45);
console.log("Is 3 <= 2?  predict false.");
console.log(3 <= 2);
console.log("Is 72 > 83 ?  predict true.");
console.log(72 > 83);
console.log("Is car == 'subaru' && car.length == 6? predict true ");
console.log(car == 'subaru' && car.length == 6);
